name: Performance Testing CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      #- name: Run linter
       # run: npm run lint

      - name: Build application
        run: npm run build

      - name: Start test infrastructure (Diagnostic Mode)
        run: |
          echo "Starting all services in detached mode..."
          docker compose build
          docker compose up -d

          echo "Waiting for 60 seconds to allow containers to initialize or fail..."
          sleep 60

          echo "-----------------------------------------------------"
          echo "Current status of all containers:"
          docker compose ps
          echo "-----------------------------------------------------"

          echo "Fetching logs from the InfluxDB container..."
          # The '|| true' ensures this step doesn't fail immediately if the container is already stopped
          docker compose logs influxdb || true
          echo "-----------------------------------------------------"

          echo "Checking the health of the test-api..."
          # This will now fail the build and show us all the logs above
          if ! docker compose ps | grep 'test-api' | grep -q 'healthy'; then
            echo "Services did not become healthy. See logs above for details."
            exit 1
          fi

          echo "Services appear to be ready."

      - name: Run performance smoke tests
        run: |
          # Run k6 with a smaller load for CI.
          docker compose run --rm \
            -e VUS=50 \
            -e DURATION=30s \
            k6 run /scripts/load-test.js \
            --out xk6-influxdb \
            --summary-export=summary.json

      - name: Generate HTML Report
        run: npx k6-html-reporter --json summary.json --output report.html

      - name: Post summary to GitHub Job Summary
        run: |
          echo "### k6 Performance Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          VUS_MAX=$(jq '.metrics.vus_max.value' summary.json)
          REQ_RATE=$(jq '.metrics.http_reqs.rate' summary.json | xargs printf "%.2f")
          P95_DURATION=$(jq '.metrics.http_req_duration."p(95)"' summary.json | xargs printf "%.2f")
          ERROR_RATE=$(jq '.metrics.http_req_failed.rate * 100' summary.json | xargs printf "%.2f")
          
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| Max Virtual Users | $VUS_MAX |" >> $GITHUB_STEP_SUMMARY
          echo "| Request Rate | $REQ_RATE reqs/s |" >> $GITHUB_STEP_SUMMARY
          echo "| P95 Duration | ${P95_DURATION}ms |" >> $GITHUB_STEP_SUMMARY
          echo "| Error Rate | ${ERROR_RATE}% |" >> $GITHUB_STEP_SUMMARY

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-results
          path: |
            summary.json
            report.html

      - name: Cleanup
        if: always()
        run: docker compose down -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub (or other registry)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          echo "Building and pushing production images..."
          # Replace 'your-docker-repo' with your actual Docker Hub username or organization
          docker build -t your-docker-repo/performance-testing-ui:latest .
          docker build -t your-docker-repo/performance-testing-api:latest ./api
          
          docker push your-docker-repo/performance-testing-ui:latest
          docker push your-docker-repo/performance-testing-api:latest

      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # This is where you would add your deployment commands.
          # For example, using SSH to connect to a server and run 'docker compose pull && docker compose up -d'